<?php
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(204);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    echo json_encode(['error' => 'Method not allowed']);
    exit;
}

// ===== API KEY =====
require_once __DIR__ . '/config.php';

$input = json_decode(file_get_contents('php://input'), true);

if (!$input || empty($input['content'])) {
    echo json_encode(['error' => 'No content provided']);
    exit;
}

$audience = htmlspecialchars(strip_tags($input['audience'] ?? ''), ENT_QUOTES, 'UTF-8');
$goal = htmlspecialchars(strip_tags($input['goal'] ?? ''), ENT_QUOTES, 'UTF-8');
$content = htmlspecialchars(strip_tags($input['content'] ?? ''), ENT_QUOTES, 'UTF-8');

$goal_labels = [
    'educate' => 'Educate the audience',
    'engage' => 'Drive engagement (comments, shares, saves)',
    'authority' => 'Build authority and position as an expert',
    'sell' => 'Sell or promote a product/service',
    'awareness' => 'Increase brand awareness',
    'trust' => 'Build trust and credibility'
];

$goal_text = $goal_labels[$goal] ?? $goal;

$system_prompt = <<<PROMPT
You are an expert social media content strategist specialising in carousel content for fitness coaches, personal trainers, and health professionals on Instagram and Facebook.

Your job is to analyse draft carousel content submitted by a fitness coach and return structured improvements. The content is often generated by ChatGPT and tends to be generic, overly corporate, and lacking the punchy hooks that perform in the fitness space.

You MUST respond with valid JSON only. No markdown, no explanation outside the JSON.

Return this exact JSON structure:
{
  "score": <number 1-100 rating the original content quality>,
  "score_summary": "<one sentence explaining the score>",
  "hooks": [
    {
      "text": "<hook slide text>",
      "reason": "<why this hook works for the audience/goal>"
    },
    {
      "text": "<alternative hook>",
      "reason": "<why this works>"
    },
    {
      "text": "<bold/provocative hook option>",
      "reason": "<why this works>"
    }
  ],
  "slides": [
    "<improved slide 1 text (the hook slide)>",
    "<improved slide 2 text>",
    "<improved slide 3 text>",
    "...continue for all slides...",
    "<final CTA slide>"
  ],
  "feedback": [
    {
      "type": "issue",
      "text": "<what was wrong with the original — be specific and direct>"
    },
    {
      "type": "issue",
      "text": "<another issue>"
    },
    {
      "type": "tip",
      "text": "<actionable tip to improve their content writing in future>"
    },
    {
      "type": "tip",
      "text": "<another tip>"
    }
  ]
}

Guidelines for your improvements:
- Hooks must be punchy, specific, and scroll-stopping. No generic "Did you know..." or "In today's world..." openers. Think about what makes someone stop scrolling in a fitness feed.
- Each slide should have ONE clear idea. Remove waffle and filler words. Fitness audiences skim fast.
- Use short, direct sentences. Write how a coach actually talks to clients — not like a textbook.
- The CTA slide should be clear, direct, and match the post goal (e.g. "DM me READY", "Link in bio", "Save this for later").
- Keep the client's core message but make it sharper, more relatable, and more human.
- Avoid corporate jargon, buzzwords, and ChatGPT-style phrasing like "In the ever-evolving landscape", "Unlock your potential", "embark on a journey", or "game-changer". These kill engagement in the fitness space.
- Write like a coach talking to their ideal client — direct, confident, relatable.
- Use language that resonates with fitness audiences: transformation, results, progress, consistency, real talk.
- Feedback should be honest but constructive — help them learn to write better fitness content over time.
- Aim for 3-5 feedback items (mix of issues and tips).
- If the content is actually good, score it fairly and still offer refinements.
PROMPT;

$user_message = "Target Audience: {$audience}\nGoal: {$goal_text}\n\nCarousel Content:\n{$content}";

$payload = [
    'model' => 'claude-sonnet-4-20250514',
    'max_tokens' => 4096,
    'system' => $system_prompt,
    'messages' => [
        ['role' => 'user', 'content' => $user_message]
    ]
];

$ch = curl_init('https://api.anthropic.com/v1/messages');
curl_setopt_array($ch, [
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_POST => true,
    CURLOPT_HTTPHEADER => [
        'Content-Type: application/json',
        'x-api-key: ' . $api_key,
        'anthropic-version: 2023-06-01'
    ],
    CURLOPT_POSTFIELDS => json_encode($payload),
    CURLOPT_TIMEOUT => 60
]);

$response = curl_exec($ch);
$http_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
$error = curl_error($ch);
curl_close($ch);

if ($error) {
    echo json_encode(['error' => 'Connection failed: ' . $error]);
    exit;
}

if ($http_code !== 200) {
    $err_data = json_decode($response, true);
    $err_msg = $err_data['error']['message'] ?? 'API error (HTTP ' . $http_code . ')';
    echo json_encode(['error' => $err_msg]);
    exit;
}

$api_response = json_decode($response, true);
$text = $api_response['content'][0]['text'] ?? '';

// Extract JSON from response (handle potential markdown wrapping)
$json_text = $text;
if (preg_match('/```(?:json)?\s*([\s\S]*?)```/', $text, $matches)) {
    $json_text = $matches[1];
}
$json_text = trim($json_text);

$result = json_decode($json_text, true);

if (!$result) {
    echo json_encode(['error' => 'Failed to parse AI response. Please try again.']);
    exit;
}

echo json_encode($result);
